# GitHub Actions workflow for ZyRok iOS App Store deployment
# Save as: .github/workflows/ios-deploy.yml

name: iOS App Store Deployment

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web application
      run: npm run build
      
    - name: Install Cordova
      run: npm install -g cordova
      
    - name: Setup iOS platform
      run: |
        cp cordova-config.xml config.xml
        cordova platform add ios
        
    - name: Configure Amplify for iOS
      run: |
        mkdir -p platforms/ios/ZyRok
        cp mobile-cognito-config.json platforms/ios/ZyRok/amplifyconfiguration.json
        
    - name: Copy web build to Cordova
      run: |
        rm -rf www/*
        cp -r dist/* www/
        
    - name: Install iOS dependencies
      run: |
        cd platforms/ios
        pod install --repo-update
        
    - name: Import Code-Signing Certificates
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
        
    - name: Download Provisioning Profiles
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.zyrok.app
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
        
    - name: Build iOS App
      run: |
        cordova build ios --release --device
        
    - name: Archive and Upload to App Store
      env:
        XCODE_SCHEME: ZyRok
        XCODE_WORKSPACE: platforms/ios/ZyRok.xcworkspace
      run: |
        xcodebuild -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -archivePath "ZyRok.xcarchive" \
          -configuration Release \
          -destination "generic/platform=iOS" \
          archive
          
        xcodebuild -exportArchive \
          -archivePath "ZyRok.xcarchive" \
          -exportPath "output" \
          -exportOptionsPlist platforms/ios/ExportOptions.plist
          
    - name: Upload to App Store Connect
      env:
        APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      run: |
        xcrun altool --upload-app \
          --type ios \
          --file "output/ZyRok.ipa" \
          --apiKey "$APPSTORE_KEY_ID" \
          --apiIssuer "$APPSTORE_ISSUER_ID"
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          output/
          ZyRok.xcarchive/

# Required GitHub Secrets:
# - CERTIFICATES_P12: Base64-encoded .p12 certificate file
# - CERTIFICATES_PASSWORD: Password for .p12 certificate
# - APPSTORE_KEY_ID: App Store Connect API Key ID
# - APPSTORE_ISSUER_ID: App Store Connect Issuer ID  
# - APPSTORE_PRIVATE_KEY: App Store Connect Private Key